language: node_js
node_js:
  - node
cache: yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - mysql
before_install:
  - export TZ=Asia/Hong_Kong
  - mysql -e 'CREATE DATABASE `tinyrecord` DEFAULT CHARACTER SET `utf8`'
